export interface SubService {
  id: string;
  name: string;
  description: string;
  indication?: string;
}

export interface DepartmentService {
  id: string;
  number: string;
  category: "Audiology" | "Speech Therapy" | "Physiotherapy" | "Rehabilitation";
  headline: string;
  subheadline: string;
  summary: string;
  accentColor: string;
  bgGradient: string;
  imageHint: string;
  subServices: SubService[];
}

export const servicesData: DepartmentService[] = [
  {
    id: "audiology",
    number: "01",
    category: "Audiology",
    headline: "HEAR BETTER.",
    subheadline: "Diagnostic precision and acoustic rehabilitation for every stage of sound.",
    summary: "From pediatric hearing assessments to sophisticated digital hearing aid fittings, our audiology department pairs clinical electroacoustic testing with compassionate care.",
    accentColor: "#DDA133",
    bgGradient: "from-[#0F383B] to-[#0A2426]",
    imageHint: "audiology",
    subServices: [
      {
        id: "pta",
        name: "Pure Tone Audiometry",
        description: "Measures the softest sounds you can hear across a full frequency spectrum to precisely identify the nature, type, and degree of hearing loss.",
        indication: "Comprehensive auditory threshold mapping"
      },
      {
        id: "speech-audiometry",
        name: "Speech Audiometry",
        description: "Evaluates your ability to detect, discriminate, and comfortably comprehend human speech at varying sound intensities in quiet and noise.",
        indication: "Clarity and word recognition diagnostics"
      },
      {
        id: "tympanometry",
        name: "Tympanometry",
        description: "Objective evaluation of middle ear pressures, eardrum mobility, and ossicular chain compliance to detect fluid, perforation, or eustachian tube dysfunction.",
        indication: "Middle ear function & impedance testing"
      },
      {
        id: "oae",
        name: "OAE (Otoacoustic Emissions)",
        description: "Assesses cochlear outer hair cell viability by measuring subtle acoustic responses generated by the inner ear, crucial for infant and objective evaluations.",
        indication: "Objective cochlear & newborn screening"
      },
      {
        id: "hearing-aid-consultation",
        name: "Hearing Aid Consultation",
        description: "In-depth clinical dialogue matching your audiometric profile, auditory lifestyle, dexterity, and communication priorities to advanced amplification systems.",
        indication: "Personalized technology selection"
      },
      {
        id: "hearing-aid-trial-fitting",
        name: "Hearing Aid Trial & Fitting",
        description: "Real-ear acoustic verification, speech mapping calibration, and customized physical ear canal coupling to ensure natural sound and maximum comfort.",
        indication: "Real-ear verified precision adaptation"
      },
      {
        id: "hearing-aid-walkins",
        name: "Hearing Aid Walk-ins",
        description: "Immediate diagnostic troubleshooting, ultrasonic cleaning, receiver servicing, dome replacement, and fine-tuning for existing amplification wearers.",
        indication: "Ongoing device maintenance & calibration"
      }
    ]
  },
  {
    id: "speech-therapy",
    number: "02",
    category: "Speech Therapy",
    headline: "FIND YOUR VOICE.",
    subheadline: "Restoring communication, voice quality, and swallowing confidence across all ages.",
    summary: "Our speech-language pathologists provide evidence-based interventions for pediatric delays, stuttering, neurogenic aphasia, voice pathology, and complex swallowing disorders.",
    accentColor: "#2A5C41",
    bgGradient: "from-[#113B34] to-[#0A2621]",
    imageHint: "speech",
    subServices: [
      {
        id: "speech-delay",
        name: "Speech Delay & Language Development",
        description: "Structured developmental therapy targeting expressive vocabulary, receptive comprehension, sentence structure, and communicative social intent in young children.",
        indication: "Pediatric developmental milestone support"
      },
      {
        id: "articulation",
        name: "Articulation & Speech Sound Therapy",
        description: "Motor-phonetic training and phonological therapy to correct sound substitutions, omissions, and distortions for clear, intelligible everyday speech.",
        indication: "Phonological clarity & motor speech refinement"
      },
      {
        id: "stuttering-fluency",
        name: "Stuttering / Fluency Therapy",
        description: "Specialized fluency shaping and stuttering modification techniques designed to cultivate effortless, rhythmically steady speech and reduce communication tension.",
        indication: "Fluency regulation for children & adults"
      },
      {
        id: "voice-therapy",
        name: "Voice Therapy",
        description: "Therapeutic vocal hygiene, resonance balancing, and respiratory support for muscle tension dysphonia, vocal nodules, strain, and professional voice users.",
        indication: "Vocal cord rehabilitation & vocal health"
      },
      {
        id: "aphasia-stroke",
        name: "Aphasia & Post-Stroke Rehabilitation",
        description: "Intensive neurogenic speech re-education restoring word retrieval, auditory comprehension, reading, and pragmatic conversational expression following neurological events.",
        indication: "Neuro-rehabilitation for stroke recovery"
      },
      {
        id: "cognitive-communication",
        name: "Cognitive-Communication Therapy",
        description: "Targeted interventions focusing on memory, executive functioning, attention, and cognitive linguistic processing after traumatic brain injury or neuro-decline.",
        indication: "Executive cognitive and functional language restoration"
      },
      {
        id: "dysphagia-management",
        name: "Dysphagia / Swallowing Management",
        description: "Clinical bedside swallowing assessment, compensatory posture training, diet texture modification, and pharyngeal strengthening protocols.",
        indication: "Safe, aspiration-free deglutition care"
      },
      {
        id: "vitalstim",
        name: "VitalStim Therapy for Dysphagia",
        description: "Targeted neuromuscular electrical stimulation (NMES) carefully calibrated to co-activate pharyngeal musculature during active swallowing rehabilitation exercises.",
        indication: "Advanced electro-therapeutic swallowing retraining"
      },
      {
        id: "autism-developmental",
        name: "Autism & Developmental Disorders",
        description: "Holistic augmentative and alternative communication (AAC), social pragmatic coaching, and sensory-integrated communication therapy for neurodivergent individuals.",
        indication: "Neurodiversity-affirming communicative growth"
      }
    ]
  },
  {
    id: "physiotherapy",
    number: "03",
    category: "Physiotherapy",
    headline: "MOVE FORWARD.",
    subheadline: "Physical restoration, neurological retraining, and active movement rehabilitation.",
    summary: "Whether recovering from orthopedic surgery, regaining independence after a stroke, or optimizing mobility in aging, our physical therapists craft guided functional progressions.",
    accentColor: "#DDA133",
    bgGradient: "from-[#10383D] to-[#0A262A]",
    imageHint: "physio",
    subServices: [
      {
        id: "musculoskeletal",
        name: "Musculoskeletal & Orthopaedic Physiotherapy",
        description: "Manual joint mobilization, soft tissue therapy, and progressive loading for spinal disorders, osteoarthritis, tendonitis, and postural mechanical syndromes.",
        indication: "Spine, joint & soft-tissue pain relief"
      },
      {
        id: "neuro-rehab",
        name: "Neuro Rehabilitation",
        description: "Task-oriented neuro-facilitation, balance perturbation training, gait re-education, and motor recovery for stroke, Parkinson's disease, and neuropathy.",
        indication: "Central and peripheral neural retraining"
      },
      {
        id: "pediatric-physio",
        name: "Pediatric Physiotherapy",
        description: "Play-based gross motor development, hypotonia management, torticollis correction, and coordination training for infants and developing children.",
        indication: "Milestone facilitation & developmental movement"
      },
      {
        id: "geriatric-physio",
        name: "Geriatric Physiotherapy",
        description: "Fall prevention programs, dynamic equilibrium conditioning, functional transfer training, and gentle joint preservation designed for senior independence.",
        indication: "Fall reduction & sustained elderly vitality"
      },
      {
        id: "sports-postsurgery",
        name: "Sports Injury & Post-Surgery Rehabilitation",
        description: "Phase-based postoperative protocols (ACL, rotator cuff, total joint replacements) focusing on controlled range of motion, strength kinetic chains, and return to activity.",
        indication: "Systematic surgical & athletic recovery"
      },
      {
        id: "electro-exercise",
        name: "Electrotherapy & Exercise Therapy",
        description: "Integration of clinical modalities (TENS, ultrasound, therapeutic heat) combined with precise therapeutic exercise prescriptions and neuromuscular re-education.",
        indication: "Pain modulation & active tissue strengthening"
      },
      {
        id: "home-visits",
        name: "Home Visits (Subject to Clinical Assessment)",
        description: "Dedicated mobile physical therapy services delivered in the home environment for bed-bound, frail, or acute postoperative patients within designated catchment areas.",
        indication: "In-home functional rehabilitation support"
      }
    ]
  },
  {
    id: "rehabilitation",
    number: "04",
    category: "Rehabilitation",
    headline: "REBUILD CONFIDENCE.",
    subheadline: "Integrated multidisciplinary care bringing all clinical disciplines together.",
    summary: "When multiple challenges intersect—such as stroke recovery requiring speech, swallowing, and physical therapy simultaneously—SHREE synchronizes your care under one unified team.",
    accentColor: "#3F7A59",
    bgGradient: "from-[#0E3537] to-[#082022]",
    imageHint: "rehab",
    subServices: [
      {
        id: "stroke-recovery",
        name: "Comprehensive Stroke Recovery Program",
        description: "Unified cross-specialty clinical pathways coordinating physical gait restoration, upper limb fine motor retraining, speech recovery, and safe deglutition.",
        indication: "Synchronized multidisciplinary neuro-rehabilitation"
      },
      {
        id: "child-development-rehab",
        name: "Multidisciplinary Child Development",
        description: "Collaborative pediatric assessment aligning speech therapy, gross motor physical therapy, and auditory processing for holistic developmental progression.",
        indication: "Integrated child growth & communicative agility"
      },
      {
        id: "senior-vitality",
        name: "Senior Vitality & Active Aging Pathway",
        description: "Synergistic hearing preservation, speech comprehension in social groups, vestibular balance training, and bone-strengthening mobility routines.",
        indication: "Independence, sensory retention & fall prevention"
      }
    ]
  }
];

export interface WhoWeHelpGroup {
  id: string;
  category: string;
  subtitle: string;
  disciplines: string[];
  description: string;
  imageHint: string;
}

export const whoWeHelpData: WhoWeHelpGroup[] = [
  {
    id: "children",
    category: "Children",
    subtitle: "Nurturing early foundations of expression & movement",
    disciplines: ["Speech & Language", "Child Development", "Pediatric Movement", "Auditory Screening"],
    description: "Gentle, play-integrated interventions supporting speech delays, articulation, sensory integration, and early motor milestones.",
    imageHint: "child"
  },
  {
    id: "adults",
    category: "Adults",
    subtitle: "Overcoming physical setbacks & communication barriers",
    disciplines: ["Hearing Restoration", "Voice Therapy", "Spine & Joint Health", "Post-Surgery Recovery"],
    description: "Evidence-driven therapeutic programs designed for busy adults seeking targeted relief from musculoskeletal strain, vocal exhaustion, or hearing changes.",
    imageHint: "adult"
  },
  {
    id: "seniors",
    category: "Seniors",
    subtitle: "Protecting balance, dignity, and active independence",
    disciplines: ["Dynamic Balance", "Fall Prevention", "Hearing Aid Fitting", "Post-Stroke Care"],
    description: "Compassionate, patient-paced rehabilitation preserving balance, cognitive-linguistic acuity, hearing clarity, and daily physical autonomy.",
    imageHint: "senior"
  },
  {
    id: "families",
    category: "Families",
    subtitle: "Empowering caregivers through every step of the journey",
    disciplines: ["Clinical Counseling", "Home Strategy Coaching", "Shared Progress Mapping", "Ongoing Support"],
    description: "Therapy doesn't stop at the clinic door. We guide parents, spouses, and caregivers with practical home routines and transparent clinical benchmarks.",
    imageHint: "family"
  }
];

export interface JourneyStep {
  step: string;
  title: string;
  subtitle: string;
  description: string;
}

export const patientJourneySteps: JourneyStep[] = [
  {
    step: "01",
    title: "Understand",
    subtitle: "Deep Clinical Listening",
    description: "Every journey begins with attentive, unhurried listening. We explore your symptoms, medical background, personal aspirations, and daily functional goals."
  },
  {
    step: "02",
    title: "Assess",
    subtitle: "Precision Diagnostics",
    description: "Using advanced diagnostic equipment—from pure tone audiometers to standardized physical mobility evaluations—we map precise baseline metrics."
  },
  {
    step: "03",
    title: "Plan",
    subtitle: "Personalized Clinical Roadmap",
    description: "Our cross-disciplinary therapists construct a transparent, realistic treatment blueprint with scheduled milestones and measurable objectives."
  },
  {
    step: "04",
    title: "Treat",
    subtitle: "Hands-on, Evidence-Based Sessions",
    description: "Targeted one-on-one therapy sessions combining cutting-edge modalities, manual techniques, speech exercises, and acoustic verifications."
  },
  {
    step: "05",
    title: "Progress",
    subtitle: "Objective Milestones",
    description: "We regularly re-measure your functional gains against established baselines, adjusting treatment intensity to ensure steady, perceptible improvement."
  },
  {
    step: "06",
    title: "Continue",
    subtitle: "Empowerment & Lifetime Care",
    description: "Transition into sustainable home exercise programs, routine hearing calibrations, and ongoing support for lifelong functional wellbeing."
  }
];
